Layout Base Terminado y Modificacion en Login
MakeSimplethings/TwitterClone pull request #12
Opened 2020-09-29 04:36 UTC by andresp2218

Layout Base 
 -> creación de archivos y la grilla esta lista, la agregue en el home porque no sabia en que parte agregarlo
Modificación en Login
-> Nombre de clase del contenedor padre, ya que este nombre era igual al que definí en el layout base.

2020-09-29 14:08 UTC, KrlosAren requested changes
Todo cool, solo eso que te deje comentado

2020-09-29 14:08 UTC, KrlosAren commented on src/pug/views/login.pug
> +		section(class="containerl")
alguna particularidad en este nombre? @andresp2218

2020-09-29 20:23 UTC, andresp2218 commented on src/pug/views/login.pug
> +		section(class="containerl")
es que yo llame a el contenedor donde iba a establecer la grilla conteiner, pero recordé que había un elemento que tenia una clase con el mismo nombre por eso cambie ese nombre y le puse un carácter que es la l de login.

2020-09-29 21:01 UTC, KrlosAren approved these changes

2020-09-30 03:58 UTC, abulnes16 commented on src/styles/scss/layout/_layoutBase.scss
> +  &__left {
Estas son variaciones de la clase container, por lo que deberian ir con **container--left** no **container__left**

2020-10-02 02:48 UTC, merged